### ISSUE TITLE
Fresh installation under 1.4.0 not working?

### ISSUE THREAD

**Issue by TELLO0815** [Sylius/InvoicingPlugin#103]
Hi there,
after fresh Sylius 1.4.0 installation (Symfony 4.2.3) I can not edit the channel anymore:

>  Neither the property "billingData" nor one of the methods "getBillingData()", "billingData()", "isBillingData()", "hasBillingData()", "__get()" exist and have public access in class "App\Entity\Channel\Channel".

In my channel entity I miss the:
`implements ShopBillingDataAwareInterface
{
    use ShopBillingDataTrait;
}`

> Also not possible to edit order status to complete. 
> InvalidArgumentException
> HTTP 500 Internal Server Error
> Sylius\InvoicingPlugin\Entity\InvoiceInterface

Or something missing in your installation docs?
Mike

**Comment by bartoszpietrzak1994** [comment]
Hello Mike!

Try installing the newest version of InvoicingPlugin (which is 0.8.1) on your fresh Sylius 1.4.0 project and BillingData-related issues should be gone. Let me know if your problems are solved.

**Comment by TELLO0815** [comment]
Hi,
channel works now. But to complete a order still brings

> InvalidArgumentException
HTTP 500 Internal Server Error
Sylius\InvoicingPlugin\Entity\InvoiceInterface

**Comment by Zales0123** [comment]
Can you pass the whole stack trace? I've just checked it on a fresh install and it works 😕

**Comment by TELLO0815** [comment]
It was just happen with the dummy orders. Created before plugin. Now i created own order, it works fine.
