### ISSUE TITLE
Make invoices and credit memos grid consistent

### ISSUE THREAD

**Issue by Zales0123** [Sylius/InvoicingPlugin#117]
Invoices and credit memos (from [RefundPlugin](https://github.com/Sylius/RefundPlugin)) are twin concepts and therefore, I believe, we should make them consistent as much as it's possible.

Looking at credit memos and invoices grids on order show page:

<img width="874" alt="Zrzut ekranu 2019-03-13 o 12 50 48" src="https://user-images.githubusercontent.com/6212718/54277056-1109b700-458f-11e9-83a0-c8dcfd8ad629.png">

And on overall indexes: 

<img width="1138" alt="Zrzut ekranu 2019-03-13 o 12 55 41" src="https://user-images.githubusercontent.com/6212718/54280180-2a166600-4597-11e9-9098-1562d45fb78a.png">
<img width="1139" alt="Zrzut ekranu 2019-03-13 o 12 55 46" src="https://user-images.githubusercontent.com/6212718/54280182-2aaefc80-4597-11e9-8852-4c5a8b2d584c.png">

we can see a lot of things that can be unified 🤖 

## Possible solution

My proposition for both invoices and credit memos overall grids is something like this: 

<img width="1168" alt="Zrzut ekranu 2019-03-13 o 14 04 59" src="https://user-images.githubusercontent.com/6212718/54281001-1c61e000-4599-11e9-9a81-98f9b7585fec.png">

1. Invoice/credit memo number
2. Order number with `#` at the beginning and a link to order show page
3. Channel name with a colorful circle
4. Total
5. Issued at date, in `Y-m-d` format
6. Buttons
    - "Show" - green, eye
    - "Download" - purple, download icon
    - "Resend" - yellow, paper plane (not needed for credit memo [for now](https://github.com/Sylius/RefundPlugin/issues/122))

On partial grids (displayed on order show page) we can get rid of 2. and 3. column, as they're irrelevant.

Tell me what you think about this proposition 🖖 I feel strongly that these two plugins can be stabilized in the very nearest future 🚀 🔥

**Comment by CoderMaggie** [comment]
I love the plan to unify these.

Although I vote for the buttons to be _greyish_ instead of colorful :)
