### ISSUE TITLE
Download/pdf.html.twig needs html tag

### ISSUE THREAD

**Issue by TELLO0815** [Sylius/InvoicingPlugin#118]
Just a little thing:
InvoicingPlugin/src/Resources/views/Invoice/Download/pdf.html.twig

To work with footer **and** header there must be the `<!DOCTYPE html>` tag.
With footer and header - there will be errors in rendering the *pdf. Like no header, but footer or no footer, but header or all white.... especially if there is lot of content (more than one side).

```
{% set shopBillingData = invoice.shopBillingData %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <style>
```

**Comment by bartoszpietrzak1994** [comment]
Hello TELLO0815!

I've read a bit of knp_snappy-related issues and it's a known issue of this package. I'm afraid that it's impossible to avoid it for now.
