### ISSUE TITLE
Extendable Entities

### ISSUE THREAD

**Issue by Prometee** [Sylius/InvoicingPlugin#120]
All Doctrine entities should be `mapped-superclass` instead of `entity` to be extendable.

For exemple my use case is to just alter the PDF generation by getting the PDF from Quickbooks or Sageone. So I just need to add a field on the `Invoice` entity to record the `external_invoice_id` and decorate `InvoicePdfFileGenerator` (download the PDF content) and `InvoiceGenerator` (create the external invoice with the APIs of Sageone or Quickbooks).

But right now I have to create a new Entity referencing a wall new table instead of just add a new field into the `Invoice` entity :$

**Comment by Roshyo** [comment]
I believe this is what they are trying to do here : https://github.com/Sylius/InvoicingPlugin/pull/97
