### ISSUE TITLE
DROP `UNIQ_16C8119E5CDB2AEB` and `billing_data_id` `taxId` sql will be generated when I run do:sc:up --dump-sql

### ISSUE THREAD

**Issue by tom10271** [Sylius/InvoicingPlugin#150]
```sql
     ALTER TABLE sylius_invoicing_plugin_invoice CHANGE channel_code channel_code VARCHAR(255) NOT NULL, CHANGE channel_name channel_name VARCHAR(255) NOT NULL;
     DROP INDEX UNIQ_16C8119E5CDB2AEB ON sylius_channel;
     ALTER TABLE sylius_channel DROP billing_data_id, DROP taxId;
```

Are some of the migration script missing?

I am using `sylius/invoicing-plugin:0.8.3`

**Comment by kortwotze** [comment]
Generate your own migration - remove all migrations from the plugin and diff your own one. Some migrations are missing and some in this plugin are just wrong. Sadly.

**Comment by diimpp** [comment]
Just did a fresh installation on sylius 1.8 and invoicing plugin 0.12.0 -- everything alright migration vise, no stray SQLs in `--dump-sql`

**Comment by GSadee** [comment]
It seems not be valid anymore
