### ISSUE TITLE
Sylius Address

### ISSUE THREAD

**Issue by RbkCp** [Sylius/InvoicingPlugin#151]
why the sylius_invoicing_plugin_billing_data table doesn't use sylius_address id ?

**Comment by diimpp** [comment]
Address is subject to changes, even address, that was tied to order shipping/billing address specifically. This plugin job is to snapshot those values at the moment of payment, therefore it have it's own address data table.

**Comment by GSadee** [comment]
I'm closing as the above answer resolves the question/issue
