### ISSUE TITLE
Resend invoice from Admin is not working

### ISSUE THREAD

**Issue by antonioperic** [Sylius/InvoicingPlugin#153]
Resend invoice is not working, the reason is because RedirectResponse is used, so event which should fire sending email is never executed.

**Comment by antonioperic** [comment]
adding event dispatcher to action, and adding this line before return RedirectResponse will fix the issue. I don't know is there any more elegant solution

`$this->eventDispatcher->addListener('kernel.terminate', function(){});`

**Comment by GSadee** [comment]
I've just checked and resending seems to work properly
