### ISSUE TITLE
Getting this error after installing

### ISSUE THREAD

**Issue by armandojf25** [Sylius/InvoicingPlugin#163]
I'm getting this error just before clicking show at orders, **Return value of Sylius\InvoicingPlugin\Entity\Invoice::channel() must be an instance of Sylius\InvoicingPlugin\Entity\InvoiceChannelInterface, null returned**

Some ideas? I can't figure out what is happening :/

Thanks in advanced

**Comment by Muspi** [comment]
Hello, same problem Here, with Sylius 1.6.0 and InvoicingPlugin 0.9

Thanks

**Comment by Gounlaf** [comment]
Duplicate #152

**Comment by GSadee** [comment]
I'm closing as it seems to be resolved already
