### ISSUE TITLE
Issue with wkhtmltopdf that generates PDF files for this plugin on default Sylius Docker

### ISSUE THREAD

**Issue by gabiudrescu** [Sylius/InvoicingPlugin#173]
If you want to use wkhtmltopdf inside default Sylius Docker from SyliusStandard, it's not enough to add this:

```
# persistent / runtime deps
RUN apk add --no-cache \
		acl \
		file \
		gettext \
		git \
		mariadb-client \
		wkhtmltopdf \
	;
```

it needs to be like this:
```
# persistent / runtime deps
RUN apk add --no-cache \
		acl \
		file \
		gettext \
		git \
		mariadb-client \
		wkhtmltopdf \
		ttf-ubuntu-font-family \
	;
```

Otherwise, the text in the PDF won't be displayed. 

I posted this as a reminder to a future-me that will have this issue again and google it and then reach this page with the solution. 

Works for me :)

**Comment by gabiudrescu** [comment]
Inspired by this solution: https://github.com/mileszs/wicked_pdf/issues/841#issuecomment-514262073

**Comment by paulmark15** [comment]
in my case I needed wkhtmltopdf to use Sylius Refund plugin. In addition to adding it like you did, I needed to copy wk files from /usr/bin/ to /usr/local/bin/, as plugin was looking for wkhtmltopdf in /usr/local/bin. So basiaclly this command:
`cp /usr/bin/wk* /usr/local/bin/`
another solution to my problem would be to change paths WKHTMLTOPDF_PATH/WKHTMLTOIMAGE_PATH in .env file, but i chose to do it the first way
