### ISSUE TITLE
Fixtures loading issue after plugin installation

### ISSUE THREAD

**Issue by senghe** [Sylius/InvoicingPlugin#176]
Hi! :)

I've installed your plugin but have an issue with loading fixtures. I've checked the commit before installation and there fixtures work correctly. 

I'm using Sylius 1.6 and your plugin in last compatible version with: ^0.10.1

![image](https://user-images.githubusercontent.com/2512726/81104808-5c112700-8f13-11ea-8cf0-12626e3f01f7.png)

Cheers! :)

**Comment by GSadee** [comment]
I'm closing the issue as it seems to be already resolved
