### ISSUE TITLE
Saving PDF to disk on generation

### ISSUE THREAD

**Issue by Vaalyn** [Sylius/InvoicingPlugin#180]
Hello, I'm currently working on a Sylius shop for the german market and I'm wondering if there are any plans to add saving the generated files to disk. Since the language of the invoice PDF can change when changing the users language (or the template, the translations, etc...) the generator might give you a different invoice file than the user received. In order to correctly archive it according to german law I need this file to be generated and stored somewhere so that I can ensure that the file that the user received has not changed.

I saw this comment on the [InvoiceEmailSender](https://github.com/Sylius/InvoicingPlugin/blob/master/src/Email/InvoiceEmailSender.php#L38) and wanted to ask if it is a conscious decision to not save the file to disk immediately after creation:

> // Since Sylius' Mailer does not support sending attachments which aren't real files
> // we have to simulate the file being on the local filesystem, so that we save the PDF,
> // run the callable and delete it when the callable is finished.

If this is not the case would you mind if I create a PR adding a configurable filesystem where those files will be stored when the `CreateInvoiceOnOrderPlacedListener` executes?

Ideally I would set this up with [oneup/flysystem-bundle](https://packagist.org/packages/oneup/flysystem-bundle) so that it can be configured to use all kinds of storage locations. Since this would add a new dependency to the plugin I would like to ask for your opinion on this ~before working on it~.

Edit: I've gone ahead and added this feature to the plugin and submitted a PR for it.

**Comment by arjanfrans** [comment]
I ran into a similar problem. I added my own customer Mailer Adapater in order to use Symfony Mailer with an async transport. However, I can't send any e-mails because the pdf files are gone before the async message handler can send the e-mail.

**Comment by michaelKaefer** [comment]
We also need this functionality.

**Comment by GSadee** [comment]
I'm closing this issue as mentioned feature has been already merged to plugin: https://github.com/Sylius/InvoicingPlugin/pull/231
