### ISSUE TITLE
Provide factories for Invoice and LineItem

### ISSUE THREAD

**Issue by mvriel** [Sylius/InvoicingPlugin#182]
In our application, we have extended the line item to include an extra field that we want to show on the PDF. But because LineItem does not have a factory class (like most other parts do) I had to duplicate the LineItemConverter. 

This may cause issues in the future when Sylius decides to change this part of the application and it would have been more durable if there was a factory that I could decorate so that I can very specifically update the LineItem in that factory (by decorating it) and then leaving the converters alone.

**Comment by GSadee** [comment]
I'm closing the issue as factories for Invoice and LineItem are already in the codebase 👌🏻
