### ISSUE TITLE
Typing problem on LineItem entity

### ISSUE THREAD

**Issue by jorisduenas** [Sylius/InvoicingPlugin#206]
Hi, 

I noticed a problem on LineItem objects. In the class we find getId() and id() which return a string like this:

[LineItem.php#L62](https://github.com/Sylius/InvoicingPlugin/blob/6ae2030e5f90a433a0f62268bda371773c4a7d0a/src/Entity/LineItem.php#L62)
```
public function getId(): string
{
    return $this->id();
}

public function id(): string
{
    return $this->id;
}
```

However, this id is configured as integer in the orm:

[LineItem.orm.xml#L5](https://github.com/Sylius/InvoicingPlugin/blob/6ae2030e5f90a433a0f62268bda371773c4a7d0a/src/Resources/config/doctrine/LineItem.orm.xml#L5)
```
<id name="id" column="id" type="integer">
    <generator strategy="AUTO" />
</id>
```

This creates typing errors.

**Comment by diimpp** [comment]
And it should be nullable as well.

**Comment by GSadee** [comment]
I'm closing the issue as it seems to be already resolved
