### ISSUE TITLE
Composer conflict

### ISSUE THREAD

**Issue by andriusvo** [Sylius/InvoicingPlugin#211]
Good day,

During latest Sylius Invoicing plugin installation, composer conflict appears:

sylius/invoicing-plugin v0.12.0 requires symfony/dependency-injection ^4.4 -> satisfiable by symfony/dependency-injection[v4.4.0, v4.4.1, v4.4.10, v4.4.11, v4.4.12, v4.4.13, v4.4.14, v4.4.15, v4.4.16, v4.4.17, v4.4.18, v4.4.19, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v4.4.8, v4.4.9].
    - symfony/dependency-injection v4.4.0 conflicts with symfony/debug-bundle[v5.2.3]

Sylius version: 1.9.1
Symfony 5.2

**Comment by GSadee** [comment]
Hello @andriusvo, this conflict should be fixed by adding support for Sylius v1.9 in https://github.com/Sylius/InvoicingPlugin/pull/212 that is already released in InvoicingPlugin v0.13.0
