### ISSUE TITLE
Invoice generating not working

### ISSUE THREAD

**Issue by niamtumihai** [Sylius/InvoicingPlugin#215]
billing_data_id and shop_billing_data_id are null when invoice is generated, also no data in there tables.  Only sylius_invoicing_plugin_invoice and sylius_invoicing_plugin_sequence tables are affected. plss help => cascade all - not woorking

ps: entities are extended

**Comment by TELLO0815** [comment]
Same problem.  `Expected a value other than null. `
Any update on this?

**Comment by GSadee** [comment]
We've checked generating invoices and it seems to work correctly, so this problem is probably not valid anymore, but of course feel free to open another issue with additional information if the problem still occurs 🖖🏻
