### ISSUE TITLE
Links with table do not seem to be right

### ISSUE THREAD

**Issue by disvroian** [Sylius/InvoicingPlugin#244]
What is the reason to use this table sylius_invoicing_plugin_shop_billing_data ? Why not link it directly to sylius_shop_billing_data ?

Same for sylius_invoicing_plugin_billing_data. Why not use the billing_address_id inside sylius_order? An invoice is link to an order only

**Comment by GSadee** [comment]
Hello @disvroian, the reason is that an invoice is an immutable entity, so we do not use relations to objects that can change over time, we only create new data objects during the generation of each invoice
