### ISSUE TITLE
[RFC] One order item splitted into multiple line items once their unit price differs

### ISSUE THREAD

**Issue by aleho** [Sylius/InvoicingPlugin#257]
A line item in Sylius for a quantity of order item > 1 isn't necessarily generated with different unit prices.

This can be caused e.g. by a discount being applied and distributed, so the sum of each item unit might not be the same.

https://github.com/Sylius/InvoicingPlugin/blob/cc71aa9265f4e6a966aef6d8f84faec291f85cd3/src/Entity/LineItem.php#L148

Comparing line items by `unitPrice` will result in invoices splitting the order items over multiple lines. This doesn't seem right to me at all, is confusing for customer and vendor (and might even be a problem with accounting, not sure).

Why are line items compared by name and unit price? This seems like a bad work-around to me (now knowing about the actual product)?

Why do you even use line items when you could be using order items?

**Comment by Snowbaha** [comment]
Hello, I had the same issue with the tax (I changed the tax rules to avoid issue but it is not the best solution).

And now, I have the same issue with same name / price : 
I proposed to compare the CODE but I don't know why it is not used : 
https://github.com/Sylius/InvoicingPlugin/pull/258

**Comment by GSadee** [comment]
Hello @aleho, as you wrote, there are some edge cases when the same units could have different unit prices. The current behavior to split units into different line items when there is a difference in its price is implemented because of accounting reasons, there is a need to have an exact price of any of units without rounding.

**Comment by aleho** [comment]
@GSadee, this might be relevant for accounting, but from a customer's point of view I've never in my entire life seen an invoice where a discount split over multiple items resulted in multiple lines with different prices.

We've had a few such invoices generated and it confused every single customer. Not even accounting understood it, nor have they ever seen a case where a customer should receive such an invoice.

This also is not an edge case, it will happen very frequently with discounts / promotions.

**Comment by CoderMaggie** [comment]
@aleho I'm Magda, the Product Owner of Sylius project. 

Having one order item splitted into multiple line items once their unit price differs was my idea 🙋🏼 . The decision was made upon logical reasons, as the invoice is an accounting document, that should present truth about prices. And now it does for sure, as it presents for how much exactly have certain order item units been bought.

I'm wondering if the real reason of confusion isn't the promotion distribution system, that has been a tear in the eye of many Sylius users already 😅 .

Let me reopen that ticket and mark it as an RFC. I will also ask the community for opinion on Slack.

**Comment by aleho** [comment]
Hi @CoderMaggie, I'm CTO for a company using Sylius Plus (I know Plus does a few things differently, so just to be sure).

We ran into this issue long before using promotions. I'm not entirely sure any more, but it seems logical to me that it was caused by another type of adjustment - taxes.

Taxes will be split evenly across order item units, if possible. If not, at least one order item unit will have a tax adjustment and total differing from the other items. I can verify this by looking at our database. This will inevitably lead to such confusing invoices being generated.

**Comment by antiseptikk** [comment]
Hi @CoderMaggie I have a particular case, the prices of the products are entered in TTC with a tax rule 20% included.
I think the product lines should be merged because we are only in the rounding context.

<img width="1488" alt="image" src="https://user-images.githubusercontent.com/1520152/179214960-0ba1db92-dd18-4660-b382-79661cf46da2.png">

**Comment by TELLO0815** [comment]
We have now the same confusion client side. Never got such invoice. They have to merged / not separated anymore.
