### ISSUE TITLE
WKHTMLTOPDF_PATH path env

### ISSUE THREAD

**Issue by web4Sylius** [Sylius/InvoicingPlugin#259]
Hello
I tried "In case wkhtmltopdf is not located in /usr/local/bin/wkhtmltopdf modify the WKHTMLTOPDF_PATH environment variable in the .env file:"
In the .env.local file, i tried : WKHTMLTOPDF_PATH="\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\""
I tried "C:\Program Files\wkhtmltopdf\bin" and more 
But when i run "php bin/console sylius-invoicing:generate-invoices"

the result : 
` The exit status code '1' says something went wrong:
  stderr: "Loading pages (1/6)
[======>                                                       ] 0%
Warning: Blocked access to file
Error: Failed to load about:blank, with network                ] 23%
  status code 301 and http status code 0 - Protocol "about" is unknown
Counting pages (2/6)                              =============] 100%

Resolving links (4/6)                    ======================] Object 1 of 1

Loading headers and footers (5/6)        ======================] Object 1 of 1

  Printing pages (6/6)
[=========================================                     ] Preparing
Done
  Exit with code 1 due to network error: ProtocolUnknownError
  "
  stdout: ""
  command: "C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe"`
  
  Thank you

**Comment by GSadee** [comment]
Hello @web4Sylius, at first glance, it looks that you have a problem with your binary of wkhtmltopdf or some permissions 🤔 However, Sylius issues should be used to report bugs, propose new features, discuss new functionalities. For everything else, please, use our Slack or stackoverflow 😃
