### ISSUE TITLE
[Bug] Resend Invoice : No error message displayed - Admin does not handle 'failure' flash type message (should be 'error')

### ISSUE THREAD

**Issue by DimGael** [Sylius/InvoicingPlugin#260]
Hello,

This issue is about resending invoice action. When I try to resend an invoice, if there's an exception thrown in the code, I get no feedback. That's because the flash message isn't displayed in the Admin Page. If I change the type from 'failure' to 'error', it get correctly displayed.

https://github.com/Sylius/InvoicingPlugin/blob/master/src/Ui/Action/Admin/ResendInvoiceAction.php#L72

For now I'll be patching it.

Also it should be interesting to log the errors thrown there because we have no feedback except a simple flash message.

**Comment by DimGael** [comment]
```
Index: vendor/sylius/invoicing-plugin/src/Ui/Action/Admin/ResendInvoiceAction.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/vendor/sylius/invoicing-plugin/src/Ui/Action/Admin/ResendInvoiceAction.php b/vendor/sylius/invoicing-plugin/src/Ui/Action/Admin/ResendInvoiceAction.php
--- a/vendor/sylius/invoicing-plugin/src/Ui/Action/Admin/ResendInvoiceAction.php	(revision 67151bc6b988f6af97f90ef09f48664c7c61b074)
+++ b/vendor/sylius/invoicing-plugin/src/Ui/Action/Admin/ResendInvoiceAction.php	(date 1638266258107)
@@ -74,7 +74,7 @@
             $this->invoiceEmailSender->sendInvoiceEmail($invoice, $customer->getEmail());
         } catch (\Exception $exception) {
             $this->session->getFlashBag()->add(
-                'failure',
+                'error',
                 $exception->getMessage()
             );
```
 
Here is the patch if needed :)

**Comment by GSadee** [comment]
Hello @DimGael, would you like to open a PR with the suggested change?

**Comment by DimGael** [comment]
After a composer update, sylius/invoicing-plugin v0.19.0 has fixed this bug :D
