### ISSUE TITLE
Question: delivery note / receipt

### ISSUE THREAD

**Issue by ahmed-bhs** [Sylius/InvoicingPlugin#280]
Hello there, I have a quick question, does the bundle support  delivery note / receipt document generation?
Cheers!

**Comment by GSadee** [comment]
Hello @ahmed-bhs, I'm sorry for the late reply. Unfortunately, I have to answer not, this plugin only provides creating and generating invoices for orders.

**Comment by GSadee** [comment]
And I'm closing this issue as this is not a feature that fits with this plugin. If that's a functionality you need and want to pay attention to it, feel free to open an issue with a feature request on the main [Sylius repository](https://github.com/Sylius/Sylius/issues).
