### ISSUE TITLE
sylius-invoicing:generate-invoices -  Expected a value other than null.

### ISSUE THREAD

**Issue by TELLO0815** [Sylius/InvoicingPlugin#301]
We use version "version": "v0.24.0" and if we want to create the invoices from existing orders sylius-invoicing:generate-invoices get ERROR:

In Assert.php line 2074:
Expected a value other than null. 

Any help/idea on this?

**Comment by GSadee** [comment]
Hi @TELLO0815!
You have provided far too little information. Above all, it would be useful to know exactly where this error is happening. Based on what you have written, I can only guess that some information needed eg. to convert to line items is incomplete.
I am closing this issue and encourage you to use [our slack](https://sylius-devs.slack.com/join/shared_invite/zt-1l2jgziyf-YavChVJasnUMS_xstCnJtg#/shared-invite/email) in the first place, and if indeed our code is the problem then reopen this issue or create a new one 🖖🏻
