### ISSUE TITLE
Price values are wrong in the PDF invoice

### ISSUE THREAD

**Issue by artyuum** [Sylius/InvoicingPlugin#306]
The tax in my shop is configured to be included in the price and I'm programmatically creating the product by providing the price (that includes the tax). However, in the PDF generated, the values regarding the price don't make sense:
![image](https://user-images.githubusercontent.com/17199757/234478333-746bcfb5-a866-4864-99d2-79f5d2304c71.png)

TTC = price including tax
HT = price without
As you can see, "Prix HT" is higher than "Prix TTC unitaire" which is not normal. Same for "Total TTC" that should be "80 €".

While in the backoffice, the values are correct:
![image](https://user-images.githubusercontent.com/17199757/234478645-a0a1e3de-89e0-4078-bb0c-1c58febc2403.png)

My temporary fix was to override the [pdf.html.twig](https://github.com/Sylius/InvoicingPlugin/blob/main/src/Resources/views/Invoice/Download/pdf.html.twig) template and copy/paste the html from `@SyliusAdmin/Order/Show/_summary.html.twig` (with some adjustments regarding the css classes, etc.) and now the data in the PDF is correct:
![image](https://user-images.githubusercontent.com/17199757/234479496-47e4c693-2cd7-401d-8db4-2ba49d6b6680.png)

**Comment by diimpp** [comment]
Invoice is merely represents all taxes as excluded from price, which doesn't make price values incorrect.

If there is some legal case, where invoice must contain taxes included in price, please present it.

**Comment by TalkMarc** [comment]
Having a configuration option to include taxes in unit prices would be a nice feature.
Here in Switzerland it's very common to include taxes in all listed Prices.
Maybe having the option to display both a unit net price excluding taxes, and a unit price including taxes would be a good compromise.

**Comment by GSadee** [comment]
Should be fixed by #307
