### ISSUE TITLE
Missing French translation 🥖

### ISSUE THREAD

**Issue by jacquesbh** [Sylius/InvoicingPlugin#44]
Hi,

Is that possible to have this plugin on crowdin please?
I would like to translate it 😃 .

Thank you!

**Comment by Zales0123** [comment]
I think that before we put it on Crowdin, we can just implement some new translation files in the plugin itself (see https://github.com/Sylius/AdminOrderCreationPlugin/pull/48). The won't get lost, if we move to Crowdin :)

**Comment by jacquesbh** [comment]
@Zales0123 The #65 doesn't close this issue.

Also, do you have any news about the crowdin integration please?
