### ISSUE TITLE
ShopBillingData on invoice show should be taken from channel

### ISSUE THREAD

**Issue by bartoszpietrzak1994** [Sylius/InvoicingPlugin#52]
Right now shop billing data is taken from

```
{% set billingData = sylius.channel.billingData %}
```

and should be

```
{% set billingData = channel.billingData %}
```

where channel should be taken from ChannelRepository using channelCode from InvoiceChannel

**Comment by lempere** [comment]
I would like to try to fix that if nobody is working.

**Comment by bartoszpietrzak1994** [comment]
Hello Guillem!

It's been a while, sorry about that - I haven't seen your comment so far. Of course, you can fix that if you would like to :)
