### ISSUE TITLE
Unnecessary TaxID field in Channel entity

### ISSUE THREAD

**Issue by Prometee** [Sylius/InvoicingPlugin#73]
There is a taxID field in Channel entity (`ShopBillingDataTrait` and `ShopBillingDataAwareInterface`) but it's not used apparently.

**Comment by Zales0123** [comment]
What do you mean by [not used](https://github.com/Sylius/InvoicingPlugin/pull/43)? :)

**Comment by Prometee** [comment]
This is not the one on `ShopBillingData` entity, this field is on `Channel` Entity see here : [ShopBillingDataAwareInterface.php](https://github.com/Sylius/InvoicingPlugin/blob/master/src/Entity/ShopBillingDataAwareInterface.php#L9)

**Comment by Prometee** [comment]
This field is not in any of doctrine migrations files but when you ask doctrine to create the entire database it appear because this field is present in [ShopBillingDataTrait.php](https://github.com/Sylius/InvoicingPlugin/blob/master/src/Entity/ShopBillingDataTrait.php#L18)
