### ISSUE TITLE
customize template

### ISSUE THREAD

**Issue by itwhy** [Sylius/InvoicingPlugin#84]
Hi, i tried to customise pdf template like other bundle but nothing change : / 

my path is Templates/SyliusInvoicingPlugin/Invoice/Download/ ..

edit : the path is actually : Templates/bundles/SyliusInvoicingPlugin/Invoice/Download/ ..

do you know why ? 

thx you !

**Comment by Zales0123** [comment]
Hello Mathieu, in fact, it should work without a problem :/ I'll try to investigate it asap and give you some feedback.

**Comment by Zales0123** [comment]
I've just checked it and indeed there is some problem with overriding 😢 Maybe it's because plugin templates are placed in `Resources/views`? Thank you for the report, anyway, we will try to find a solution as soon as possible. Of course, if you have any idea what can be wrong, feel free to contribute :)

**Comment by teohhanhui** [comment]
Could it have anything to do with Symfony's bundle naming convention?

**Comment by itwhy** [comment]
haha, i'd really like to help ! but i'm just a "user", and very sylius noob :)

**Comment by itwhy** [comment]
hi guys, any news for this issue ?

**Comment by bartoszpietrzak1994** [comment]
Hello Mathieu,

Unfortunately, there's a bug in Sylius due to a conflict between new Twig and Sylius' ThemeBundle conventions since 1.3.1 version. Although we are working on a solution, right now I'd suggest downgrading Sylius to 1.3.0 version if you are in a hurry.

**Comment by nemoneph** [comment]
Hello,
I'm facing the same problem on 1.4-BETA.

Any news on this ?
Thx :)

**Comment by bartoszpietrzak1994** [comment]
Hello @itwhy @nemoneph !

We've managed to dig into this problem and managed to find a solution that allows us to customize templates under `templates/Bundles/SyliusInvoicingPlugin` path. 

The new version of SyliusInvoicingPlugin has just been relased (`v0.8.3`) so please update it via composer and let us know if everything works like a charm :)

**Comment by itwhy** [comment]
hi guys, 
sorry i found another way to do it (app/Ressources/SyliusInvoicingPlugin/) and i'm now too late to test the new way, the deadline is too close.
i'll try that in the next v.
anyway, thx you ! hope this will help others guys ^^
